=== javiergf10/Marcas2/XML y DTDs (T1, 2 y 3)/Nueva carpeta/Ejercicio1DTD.dtd
<!DOCTYPE declaraciones SYSTEM "Ejercicio1XML">
<!DOCTYPE declaraciones [
  <!ELEMENT declaraciones (consonante, variable+, tipo_de_dato+)>
  <!ELEMENT consonante (#PCDATA)>
  <!ELEMENT variable (#PCDATA)>
  <!ATTLIST consonante valor CDATA #IMPLIED>
  <!ATTLIST variable tipo CDATA #IMPLIED>
  <!ELEMENT tipo_de_dato (fecha, hecho)>
  <!ELEMENT fecha (#PCDATA)>
  <!ELEMENT hecho (#PCDATA)>
]>

=== javiergf10/Marcas2/XML y DTDs (T1, 2 y 3)/Nueva carpeta/Ejercicio1XML.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE declaraciones SYSTEM "Ejercicio1DTD.dtd">
<declaraciones>
   <consonante valor="3.141592">PI</consonante>
   <variable tipo="real">radio</variable>
   <variable>area</variable>
   <variable>longitud</variable>
   <tipo_de_dato>
      <fecha>20 de julio de 1969</fecha>
    <hecho>Llegada del hombre a la Luna</hecho>
    <hecho>Aterriza el hombre en la Luna</hecho>
   </tipo_de_dato>
      <tipo_de_dato>
      <fecha>22 de julio de 2009</fecha>
       <hecho>Se estrena Avatar</hecho>
   </tipo_de_dato>

</declaraciones>

=== javiergf10/Marcas2/javascrip/XML y DTDs (T1, 2 y 3)/Nueva carpeta/Eje 1 Completo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<!DOCTYPE declaraciones SYSTEM "Ejercicio1XML"> -->
<!DOCTYPE declaraciones [
  <!ELEMENT declaraciones (consonante, variable+, tipo_de_dato+)>
  <!ELEMENT consonante (#PCDATA)>
  <!ELEMENT variable (#PCDATA)>
  <!ATTLIST consonante valor CDATA #IMPLIED>
  <!ATTLIST variable tipo CDATA #IMPLIED>
  <!ELEMENT tipo_de_dato (fecha, hecho+)>
  <!ELEMENT fecha (#PCDATA)>
  <!ELEMENT hecho (#PCDATA)>
]>
<!-- <!DOCTYPE declaraciones SYSTEM "Ejercicio1DTD.dtd"> -->
<declaraciones>
   <consonante valor="3.141592">PI</consonante>
   <variable tipo="real">radio</variable>
   <variable>area</variable>
   <variable>longitud</variable>
   <tipo_de_dato>
      <fecha>20 de julio de 1969</fecha>
     <hecho>Llegada del hombre a la Luna</hecho>
      <hecho>Aterriza el hombre en la Luna</hecho>
   </tipo_de_dato>
    <tipo_de_dato>
        <fecha>22 de julio de 2009</fecha>
       <hecho>Se estrena Avatar</hecho>
        
   </tipo_de_dato>
</declaraciones>
